### ISSUE TITLE
Register module

### ISSUE THREAD

**Issue by janschopohl** [TUM-LRR/era-gp-sim#10]

**Comment by FelixOpolka** [comment]
Added commit 180bdca97d6c8c4b0f239b016f7975a1a00be90b "_Merge branch 'feature/gui' into feature/gui-register-component_"

**Comment by FelixOpolka** [comment]
Added commit 0abdb805394be965487a9862f4a7a579bc583597 _"Updated main to use new constructor"_

**Comment by k-lukas** [comment]
From my point of view, everything looks good. Just a small convenience tip:
If you iterate over the registers like this: `for (const auto &registerItem : unitRegisters) { ... }` you have to call `get()` on every `registerItem`, because its a reference wrapper. This can be automatically done by the compiler, if you use the for loop like this: `for (const RegisterInformation &registerItem : unitRegisters) {...}`. Then you can omit the `get()`calls.

**Comment by riedersa** [comment]
In my opinion it is fine.
