### ISSUE TITLE
GuiProject

### ISSUE THREAD

**Issue by riedersa** [TUM-LRR/era-gp-sim#101]

**Comment by riedersa** [comment]
Sorry, I forgot to open an issue. This belongs to branch Feature/gui-guiproject

**Comment by kreudom** [comment]
Hi, looks pretty good. 

The only thing i noticed are some documentation inconsistencies in `gui-project.hpp`. Sometimes you use Javadoc-syntax (`@param`) instead of doxygen syntax (`\param`) and some comments exceed the 80 characters line length.

But apart from these very minor style issues I don't see any problems.

**Comment by FelixOpolka** [comment]
Hello,

looks good to me; I haven't spotted anything apart from what Dominik has mentioned. Except maybe that there are quite a few typos in the comments.
