### ISSUE TITLE
Add arguments to compile error

### ISSUE THREAD

**Issue by davschneller** [TUM-LRR/era-gp-sim#102]
Branch: https://github.com/TUM-LRR/era-gp-sim/tree/feature/compile-error-arguments

**Comment by davschneller** [comment]
Hi,

thanks for doing this!
Some questions:
* Isn't for example here some `P_TR` missing? (https://github.com/TUM-LRR/era-gp-sim/blob/4aea7c3d13630fcebb8d43a5cabe4a634961c5ab/include/parser/string-parser.hpp#L101)
* Wouldn't it be nice to instead of having to write for example `addError(P_TR("whatever"))` just to write `addError("whatever")` but with addError being a macro itself which expands then to `addError(P_TR("whatever"))`? Or is there anything in C++ that would prevent this? This would also drastically reduce the source of possible lost translations or whatever you might want to call them.
* Is it really necessary to have `const char *` constructors instead of `const std::string&` ones, especially after the cast from the latter to the first one is automatic, and going the reverse direction is also possible... (though arguably this might increase the risk of possible lost translations, maybe...)
* When I actually thought of arguments in the CompileError, I rather thought about adding some String-Vector with arguments to them... Why is it now needed to include the translateable? Wouldn't it be sufficient to use std::strings with the translation marking macro to convert it later on? (for myself, I'd like it more, if the translateable would not have to be included basically everywhere (and kept out from the parser) where something is translated, rather than using it then solely by the GUI; but ok, that's just a personal opinion) (something that would be really nice though are convenience constructors within CompileError and convenience methods within CompileState which support arguments, maybe even variadic ones (would also work with the macros suggested above), so we do not have to write Translateable::createShared and so on all the time)

If you need any help, I am ready to do so. (by the way, I am currently working on a bit of refactoring of the parser (has no real issue right now))

**Comment by ErikP0** [comment]
1. Thank you, I actually overlooked this one
2. The way the Qt-Translation works is that some instance of a Qt-Translater scans through the source code and gathers all literals that need translation. These literals can then be translated and the result is saved in some kind of translation table, mapping the literal and the translated version. We were not planning to actually create such table, so we just mark all literals for translation. This means the string **literal** (to be more specific, a `const char[n]` where n is a fixed number) must be enclosed by the `QT_TRANSLATE_NOOP` macro in order to be found. Enclosing a `std::string` later would not be possible, as its value is only known at runtime. So unfortunately we need to enclose every single literal.
3. As the way the translation works, such a expression is also not valid: `P_TR("bla bla"+a_value+"more bla bla")` because the source code scanner cannot determine the literal as it is dependent on `a_value`. I tried to implement the constructors the way, that such a expression will result into a compile error rather than a missing marked translation which won't generate an error (neither compile nor runtime). The expression is determined to be of type `std::string` while any pure literal (like `"bla"`) is of type `const char*`. So I need to forbid a `std::string` as argument because it may contain an appended runtime value. Therefor I can unfortunately only allow `const char*` for that.
My thoughts were, that if somebody will later add more error messages and uses `"bla"+a_value` as his message then he will get a compile error and then (hopefully) realize that the right way of marking his message for translation is using a `Translateable` with the literal parts of his message as base string and `a_value` as runtime arguments.
4. It is possible to just use a message and its arguments. Then we would need the argument injection and translation code for the compile error. The exact same structure of message and arguments is also needed for generating translateable context information messages for instructions (and is also needed for `ValidationResult`). So we would write the same code of translating the base string/ injecting the arguments 3 times. The `Translateable` is the abstraction, so we only need to write the code once.
I didn't really think about the Qt-include, I will change the Translateable to be just a base string and the vector of arguments. In a seperate class/function, I will implement the argument injection, translation and the creation of the QString. So the Translateable itself will only be C++, while the GUI can then use both parts to show the message.
I will also add variadic convenience functions, good idea.

@goldsborough also critized the whole translation data being in the source code. I also admit, it is not the best nor nicest way, but the translation process was chosen early (at that point when we introduced `AbstractSyntaxTreeNode::validate`) by the team. Changing it now would really cost time. We could just remove those markers and all limitations and use normal strings, but then we have to be able to live without the translation (we would still have the message data in the code, though). But this decision must be made by the whole team.
