### ISSUE TITLE
Serialization

### ISSUE THREAD

**Issue by ProfPille** [TUM-LRR/era-gp-sim#113]

**Comment by janschopohl** [comment]
- Please document all members of Memory
- Please add inline documentation in the source code to non trivial methods
- there should be an underscore [here](https://github.com/TUM-LRR/era-gp-sim/compare/feature/memory-serialization#diff-983c410bcfce50bda54c5204f09d47adR186)
- why have you changed the behaviour of the `Memory::get` and `Memory::set/put`
- Why is [this](https://github.com/TUM-LRR/era-gp-sim/compare/feature/memory-serialization#diff-b012a5be3222f19f5e0fdc92fd90d1fdR95) not a private member
- [This](https://github.com/TUM-LRR/era-gp-sim/compare/feature/memory-serialization#diff-b012a5be3222f19f5e0fdc92fd90d1fdR161) overload does not seem to make sense, as the rvalue paramter is converted to a lvalue...
- The serialization process seems a bit too complicated in my opinion, as we don't need a variable 'line length'. I think it would be easier to directly iterate through the memory cells and write the data into the json object directly.
- consider using private members instead of unnamed namespaces. They make it quite hard to read the code, because they are missing from the header and lack documentation. They also make the source file seem quite unstructured and bloated.

**Comment by davschneller** [comment]
Jan has already pointed out all the important issues, so there's nothing more left to say! Comments and a bit less of complexity in the methods would be great. But if apart from that it seems to work I think, so it's nice (when the issues are corrected, it's even better).

**Comment by janschopohl** [comment]
- add something like `using Json = nlohmann::json` to make your code more readable
- document all private members of the Register class and improve the formatting of the comments. Currently, they are not consistent with all other doxygen comments, because they are after the declarations, which makes it harder to read.
- look for includes that you only need in the source file, for example [this](https://github.com/TUM-LRR/era-gp-sim/blob/c57b5618208e3569239466d2fbe8d7d486d914c9/include/core/register-set.hpp#L29) 
- [TODO?](https://github.com/TUM-LRR/era-gp-sim/blob/c57b5618208e3569239466d2fbe8d7d486d914c9/source/core/register-set.cpp#L243)
- Again, I don't think [this](https://github.com/TUM-LRR/era-gp-sim/blob/c57b5618208e3569239466d2fbe8d7d486d914c9/source/core/register-set.cpp#L207) overload is needed. I think you should not require an argument in the serialize method at all, you should just create a json container.
- use `j_map(data)` to create a json object of the map. This would also improve the format of your json file, see next point
- The format of your json file is quite strange, this is the output of your test:

```
{
    "register_#RegisterBadLuck": "4C2B3A57",
    "register_AND_TIRED": "6266D6F2",
    "register_I'D_LOVE_TO": "6C74A409",
    "register_I_AM_HUNGRY": "A5595115",
    "register_I_AM_KINDA_NOT_VERY_CREATIVE_TODAY": "97C4AA2F",
    "register_I_HAVE_GREAT_IDEAS_FOR_OTHER_THINGS_THO": "9A4EB343",
    "register_I_NEED_LOTSA_UNIQUE_NAMES": "8C7F0AAC",
    "register_I_WANNA_GO_HOME_NOW": "7005B724",
    "register_LET_IT_GO": "9FA1DED3",
    "register_NOT_A_REGISTER": "E84BDD8",
    "register_PROBABLY_NOT": "8B7D76C3",
    "register_SO_MANY_POSSIBILITIES": "B716A675",
    "register_THAT'S_TOO_BAD": "D8E57D67",
    "register_THE_VERY_LAST_REGISTER": "E44B3C46",
    "register_WOULD_IT_BE_LEGAL_TO_USE_A_SONGTEXT_AS_CONSTANT?": "DBA252FB",
    "register_YAY_FOR_REGISTER_NAMES": "D821CCC0",
    "register_parent_vector": [
        "I_NEED_LOTSA_UNIQUE_NAMES",
        "I_AM_KINDA_NOT_VERY_CREATIVE_TODAY",
        "SO_MANY_POSSIBILITIES",
        "YAY_FOR_REGISTER_NAMES",
        "I_HAVE_GREAT_IDEAS_FOR_OTHER_THINGS_THO",
        "WOULD_IT_BE_LEGAL_TO_USE_A_SONGTEXT_AS_CONSTANT?",
        "PROBABLY_NOT",
        "THAT'S_TOO_BAD",
        "I'D_LOVE_TO",
        "LET_IT_GO",
        "I_AM_HUNGRY",
        "AND_TIRED",
        "I_WANNA_GO_HOME_NOW",
        "#RegisterBadLuck",
        "THE_VERY_LAST_REGISTER",
        "NOT_A_REGISTER"
    ]
}
```

Instead of saving each register name and value pair as a single object, use an json map. I don't see a reason to add the 'register' prefix to each name, as I think the final file will be something like this:

```
{
...
"registers" : {
        [Your json output]
    }
...
}
```

**Comment by janschopohl** [comment]
I just saw that you added a `Memory::clear` method [here](https://github.com/TUM-LRR/era-gp-sim/commit/08585d336b43b75144b99a557f3284ac8afb272c#diff-b012a5be3222f19f5e0fdc92fd90d1fdR236), but I think that would not call `_wasUpdated`. Please add a `_wasUpdated` call with 0 as address and the size of the memory as amount.

**Comment by davschneller** [comment]
Just a few small things (apart from Jan's suggestions):
- The last commit (above this post) seems to be for big int, is that intended?
- Shorter methods would would be really great and would help to make the code more easily understandable.

Apart form that and the things Jan mentioned as suggestions, I currently got nothing more to add. Sorry for the late review reply.

**Comment by janschopohl** [comment]
- Your serialization methods don't need a json object as parameter.

#### Memory
- you can convert the std::map directly to a json object, then you don't need [these](https://github.com/TUM-LRR/era-gp-sim/blob/feature/memory-serialization/source/core/memory.cpp#L160) for loops
- the numbering of the lines/cells seems strange in the output: `"memory_line9989":"91;","memory_line999":"B5;","memory_line9990":`
- Again, if you directly convert it to a json map, you can remove the `memory_line` prefix and it would be way cleaner
- please use `using json = nlohman::json` or something like this
- your test might not sufficiently test edge cases, like a value at the beginning of the memory, then only zeros and a value at the ends
- default to lineLength=1 like we discussed in the meeting
- some of the points of my last review are not implemented, for example the formatting of the comments of private members

#### Registers
- You can probably delete [this](https://github.com/TUM-LRR/era-gp-sim/blob/feature/register-serialize/source/core/register-set.cpp#L212)
- It would be nicer to generate a `std::map<std::string, std::string>` instead of a `std::map<std::string, MemoryValue>` (directly convert the memory values to hex strings). This way you wouldn't need [this](https://github.com/TUM-LRR/era-gp-sim/blob/feature/register-serialize/source/core/register-set.cpp#L208) loop and it is easier to understand
- Remove the `register_value` prefix
