### ISSUE TITLE
Add a sleep method to the core

### ISSUE THREAD

**Issue by janschopohl** [TUM-LRR/era-gp-sim#130]

**Comment by goldsborough** [comment]
- Well, `sleep` doesn't really have anything to do with accessing memory, so on first sight this might seem odd. We can make an exception for now, but if we add more functionality that doesn't have anything to do with memory accesses, we may want to rename it to `coreAccess` or something.
- [here](https://github.com/TUM-LRR/era-gp-sim/commit/37bfe16ded0ee598771c4a6cccbef3a14f1202a6#diff-46637d5d87bfcb1468638bdb7f243681R30) I would store `zero` in a static variable to make the condition shorter.
- If understand correctly what you are trying to do in `sleep` is to poll in 100ms intervals to see if the stop flag was set in the meantime (i.e. if the user stopped the sleep)? From a concurrency point of view, what you are trying to achieve is usually done with a [condition variable](http://en.cppreference.com/w/cpp/thread/condition_variable). A condition variable is a concurrency primitive that lets you sleep until a condition is met, which can be fired using `notify` calls (like `wait`/`notify` in Java). You would then set a timeout as well using `std::condition_variable::wait_for`, so that you either sleep until someone calls `notify` or the timeout times out, which is what we want here :blush: Please look into it, it's good to know anyway :)

**Comment by ErikP0** [comment]
Hi, I reviewed your code to speed up the process, as I need your functionality in #120.
Your implementation looks solid, but I prefer @goldsborough's approach with the condition variable. Using it may even make your code simpler as you don't have to count down the sleep time in 100ms steps.
I'm looking forward to your feature!
