### ISSUE TITLE
refactor execution loop

### ISSUE THREAD

**Issue by janschopohl** [TUM-LRR/era-gp-sim#131]

**Comment by goldsborough** [comment]
- We could make this look slightly more readable [here](https://github.com/TUM-LRR/era-gp-sim/commit/12ecd98d26cc738739c102137fc3c3cc4e0e3aaf#diff-98217b5ef8256dd0fac6e3d65ad62d2fL66):

```
auto nextNode = _findNextNode();
while (true) {
  if (!_stopFlag.test_and_set()) break;
  if (nextNode >= _finalRepresentation.commandList.size()) break;
  if (!_executeNode(nextNode)) break;
  nextNode = _updateLineNumber(nextNode);
```
- Also in cases like [here](https://github.com/TUM-LRR/era-gp-sim/commit/12ecd98d26cc738739c102137fc3c3cc4e0e3aaf#diff-98217b5ef8256dd0fac6e3d65ad62d2fR218) I prefer a explicit, individual checks without having to break a line:

```
if (_finalRepresentation.hasErrors()) return false;
if (nodeIndex >= _finalRepresentation.commandList.size()) return false;
```
- `auto` [here](https://github.com/TUM-LRR/era-gp-sim/blob/12ecd98d26cc738739c102137fc3c3cc4e0e3aaf/source/core/parsing-and-execution-unit.cpp#L222):

```
  // reference to avoid copying a unique_ptr
  FinalCommand &currentCommand = _finalRepresentation.commandList[nodeIndex];
  // check for runtime errors
  ValidationResult validationResult =
      currentCommand.node->validateRuntime(_memoryAccess);
```

Otherwise fine. I'm a bit concerned that the class is already quite large (just judging by the initializer list). It's fine now, but if more logic comes in, we may have to consider refactoring (in the future).
