### ISSUE TITLE
Implement Pseudo Instructions using Macros

### ISSUE THREAD

**Issue by k-lukas** [TUM-LRR/era-gp-sim#136]

**Comment by ErikP0** [comment]
Hi,
Your implementation looks solid. Some suggestions:
- A test would be nice to see if all pre-defined macros compile
- It looks like your ommited `lb, lh, lw, ld` and `sb, sh, sw, sd` pseudo instructions. If this is due to a conflict with instructions with the same mnemonic, I suggest to implement them under a different name (like `loadb, loadh, ...` and `storeb, storeh, ...` respectively)
