### ISSUE TITLE
Add help/context messages to Instructions

### ISSUE THREAD

**Issue by ErikP0** [TUM-LRR/era-gp-sim#141]

**Comment by ErikP0** [comment]
For the reviewers:
Please also have a close look on the actual instruction documentation/help texts.
With this in code

``` C++
 auto formula = ArchitectureFormula("riscv", {"rv32i"});
  ProjectModule project = ProjectModule(formula, 64, "riscv");
  Architecture arch = project.getArchitectureAccess().getArchitecture().get();
  InstructionContextInformation docs(arch);
  QString result = "";
  for(auto instr : arch.getInstructions()) {
      result.append(docs.getContextInformation(instr.second).translate(_qmlApplication));
      result.append("<br>");
  }
  std::cout << result.toStdString() << std::endl;
```

you can print all texts into the console and then view it by copying into a file (and then open the file with a browser since it is html formatted).
Please read closely and report any spelling errors or grammar mistakes.
Thank you :)

**Comment by ProfPille** [comment]
The code looks good :D

**Comment by goldsborough** [comment]
Just checking by. Some things:

* The enum members are not very descriptive. From reading them, I have no idea what `S_SYNTAX` is. Prefer using  full names :blush:
* The hash function could be a bit more generic and standards-compliant. I recommend putting this:
```
  template<typename Enum, typename = std::enable_if_t<std::is_enum<Enum>::value>>
  struct EnumHash {
    using argument_type = Enum;
    using result_type = std::size_t;
    using underlying_type = std::underlying_type_t<Enum>;
    
    result_type operator()(const argument_type& argument) const {
      const auto ordinal = static_cast<underlying_type>(argument);
      return std::hash<underlying_type>{}(ordinal);
    }
  };
```
into the Utility namespace and then `using Hash = Utility::EnumHash<Key>;`.
* Make an alias for `std::initializer_list<const std::string>` (like `StringList`)
* Could use `std::array<std::string, 3>` if you're not planning on having more than those three colors. Also prefer putting static members right below the `private:` label, before methods and non-static data members.
* Don't define functions in the header (`_hasKey`), even small ones. It makes it harder to know where to look for definitions if you have them spread across the header and the implementation file.
* The "a" [here](https://github.com/TUM-LRR/era-gp-sim/commit/692520661cf79692b98e4c27a5bbd265a80c5128#diff-4b31581558d15d520bfdfce41b402d92R393) won't work because it's "a signed" but "a__n__ unsigned". You'll have to put that into the string you pass, or just pass two booleans/enum members for the signedness of the two parameters and then format the string accordingly.
}
* [no](https://github.com/TUM-LRR/era-gp-sim/commit/692520661cf79692b98e4c27a5bbd265a80c5128#diff-35ff806645c3692e8a7dfa5c59cba6ccR58)

To be honest, I don't really agree with writing the documentation in code, as we did here. We could have defined some HTML templates and then used a templating engine like [Jinja](http://jinja.pocoo.org) to write the documentation. The code implementation would have just needed to load the HTML files. This is precisely why we/I came up with the elaborate mechanism of defining architectures in YAML files. It makes it easier to edit them, keeps the code less noisy and separates business logic from "data". This will make it very hard to make changes. Every time we change a spelling mistake or add one line of documentation, we'll have to recompile the whole project. Either way, it seems to be working and it's too late to change now. Good job anyway :)
