### ISSUE TITLE
Load and save snapshots

### ISSUE THREAD

**Issue by janschopohl** [TUM-LRR/era-gp-sim#145]

**Comment by ErikP0** [comment]
Hi, this review is for #144 and #145:
Most of it looks fine, I have a few suggestions:
1. `GuiProject::_throwError` could make use of `common/translateable` which encapsulates a translateable message with runtime arguments. I also recommend to add a title to the error (`_throwError(const std::string& title, const Translateable& msg)` so that a runtime error can have a different error title than a error when saving.
2. In the snapshot graphical component, when starting the editor, the load button is partially covered (see pic)
3. I suggest to rename `File -> Save` and `File -> Save as` to something like Save code/Save code as to make it a bit more clear.
4. The popup dialog of `File -> Save Snapshot` needs a bit more description. E.g window title: "Save snapshot to disc"; Text: "Saves a snapshot (current register and memory content) for later use and distribution. Your snapshot can be found here: <path_to_snapshot_folder>"

**Comment by ErikP0** [comment]
![snapshot_comp](https://cloud.githubusercontent.com/assets/18466680/20749313/190230e6-b6f2-11e6-905c-2e6beec590cb.PNG)
