### ISSUE TITLE
define Memory

### ISSUE THREAD

**Issue by ProfPille** [TUM-LRR/era-gp-sim#15]

**Comment by davschneller** [comment]
Hi, I'm guessing that the methods shouldn't do anything for now. :D
Some points:
- Shouldn't the memory endiannesses be a bit more explained? And what about other, more rare memory endianness formats like mixed or middle endian (see Wikipedia, I think)? Or have we decided that we will not support them for now?
- Shouldn't it be `address` instead of `adress`? :D

Other than that, I'm fine with it if I just look at the code. Might still have to try to compile it, but as this is just a definition... (nevertheless, we really need automatic builds, they're great!) Would you mind to format it with `clang-format` though?

**Comment by davschneller** [comment]
Hi again,

Looking good, well commented, so I only have some questions left:
- What about endianness? How is it determined? Or is this the task of a different unit?
- Shouldn't `wasUpdated` actually be `hasBeenUpdated` in English? (but this is just a really minor comment)
- Maybe multiple listeners? This is absolutely not required to be implemented if you do not want to (after all, we do not needed).
- What about threads & listeners actually?

Apart from that, I am currently fine with it, keep up the good work. Bye!
