### ISSUE TITLE
define Registers

### ISSUE THREAD

**Issue by ProfPille** [TUM-LRR/era-gp-sim#16]

**Comment by davschneller** [comment]
Hi again, some points here:
- According to the styleguide, struct do not have trailing underscores to their members.
- Again, the `adress` typo (should be `address`).
- Your code looks a bit tight to me. Mind a few empty lines? ;)
- Couldn't you leave these huge `pair`-thingies away? Would make the code a bit more readable.
- And why do you make your string a string again?
- `for(int i=end-begin;i-->0;)` please don't... We don't need the one machine instruction, but I'll take it to the group just to make sure it's not my personal feeling. (`for (int i = end - begin; i > 0; --i)` or so would be nice, there always has to be a space after a `;`) Oh, and according to the styleguide it has to be prefix `--`.
- Around the for-loop, the code is a bit hard to read, because there a hardly any spaces...

And again, the recommendation to use `clang-format`. ;) If nothing else happens, I'm fine with this branch, though I'm not sure if I have taken everything into consideration. So, if you hear nothing from me again and the things above are fixed, I have nothing more to complain.

**Comment by davschneller** [comment]
Ok then, I asked in the group, and they agreed to me (as far as they answered) concerning the `for` statement.

**Comment by davschneller** [comment]
Hi again! So let's do the review again... Looks great by the way. Just these few points, then you got my OK:
- Documentation would be really great. Documentation to all and everything (and every trivial method). And doxygen.
- `void aliasRegister(const std::string &name, const std::string &parent, const std::size_t begin, std::size_t end);` has a non-const `std::size_t` member. As you have `const`ed all other members, you might change that too. But it is not necessary at all, not needed to pass the review.
- For members in structs, we do not have the `_` prefix according to the style guide. Might change that in `RegisterId`?

That's all for now. I am not a C++ expert, but as far as I know, the rule of five thing is not necessary, but it does not harm. Still, it might reduce the amount of methods to be commented. ;)

**Comment by davschneller** [comment]
Oh, and the failed Travis build result is not related to the register feature, as far as I see, that's no reason to not let you pass.

**Comment by davschneller** [comment]
Will there ever be added documentation to the methods in THIS specific branch? If not, mind closing it, as it is already merged?
