### ISSUE TITLE
Introduce simple intermediate form

### ISSUE THREAD

**Issue by davschneller** [TUM-LRR/era-gp-sim#17]

**Comment by davschneller** [comment]
Hi, this patch might be a bit big... And is it right to include the Doxyfile?

**Comment by kreudom** [comment]
Hi, I just have a few suggestions:
- I would remove the Doxyfile and the Doxygen line in .gitignore, since doxygen is already set up with a slightly different folder structure in master.
- According to our style guide file names need to be all lowercase.
- You accidently added source/arch/AbstractNodeFactories.s to the commit.
- CodePosition.hpp misses an `#include <utility>` for std::pair.
- CompileError.hpp misses an `#include <string>`.
- Tests are in the "tests" folder (instead of "test") in master, so I'd adjust that as well.

**Comment by goldsborough** [comment]
I'm just stumbling by and noticed some things too:
- The includes should be relative to the `include/` folder i.e. includes should then follow the directory structure from there e.g. `parser/foobar.hpp`. You might need to adjust your editor's settings
- `kConstant` is valid according to the style guide, but most of us are using `CONSTANT`. It's a bit easier read tbh. Regular expressions can't do replacement unfortunately, so you might want to write a Python script to do the replacement :)
- `inline` is unnecessary, always

Really like the structure and code though. Good job

**Comment by davschneller** [comment]
Thank you very much for all your suggestions! I tried to fix them, is it OK now for you?

**Comment by kreudom** [comment]
Everything looks fine to me now.

**Comment by davschneller** [comment]
Thanks, but the other reviewer is still missing... But I think that we really got to get forward (also, sorry that my patch came so late), so is anybody against that I just merge this feature now into master?
