### ISSUE TITLE
Define parser interface

### ISSUE THREAD

**Issue by davschneller** [TUM-LRR/era-gp-sim#18]

**Comment by davschneller** [comment]
Hi, everything looks pretty good! For my part, can already close this feature, yet I have just some suggestions:
- According to the styleguide, naming enum values with `CAPS_LOCK` like macros is allowed, but since a few years, it is rather done like 'kCamelCase' like constants in the style guide.
- The get methods for syntax highlighting are ok, but I fear that it might escalate with them the more different things we have to highlight... But maybe this is just me... (if not, what about putting each thing to highlight in a separate class and use inheritance? Or is this maybe too slow?)

**Comment by ErikP0** [comment]
Hi, I have reviewed your code.
Everything seems to be fine, there are only some minor points.
- You may change the define-Guard ending with HPP as it then represents the correct filename
- As you have explicitly defined the destructor you may as well explicitly define the default constructor (for consistency)
- I suggest that you include "arch/common/ast.hpp" instead of "arch/common/abstract_node_factories.hpp" as you don't use the factories but the AbstractSyntaxTreeNode-class defined in ast 
  (There is an update to ast on it's way to remove the template-characteristic; When the update is ready, I suggest you switch the include)

**Comment by kreudom** [comment]
Hi, thanks for your suggestions. I've changed the things you mentioned, please have another look if everything's fine now.

**Comment by ErikP0** [comment]
Hi,
From my point of view, you can now merge this feature.
