### ISSUE TITLE
Implement task scheduler

### ISSUE THREAD

**Issue by TobiasHoll** [TUM-LRR/era-gp-sim#21]

**Comment by goldsborough** [comment]
- The include guard should have the `ERAGPSIM_` prefix (remember to use the scripts)
- `result.hpp` is missing docs

```
template <class ResultType>

/**
 * A class to store either a value of type ResultType or an exception
 *
 */
class Result {
```

Might want to move the template parameters above the class (under the docs), looks a bit weird ([link](https://github.com/TUM-LRR/era-gp-sim/blob/feature/task-scheduler/include/core/result.hpp#L26)).
- `using Task = std::function<void()>` would be nice sugar in `scheduler.hpp`
- Why are `scheduler.hpp`'s methods defined in the header (and not in the non-existent source file)?
- s/`#include "lockfree-queue.hpp"`/`#include "core/lockfree-queue.hpp"`
- Also document the private variables:

```
/** A boolean flag indicating whether the scheduler should interrupt its event loop (oder so). */
bool _interrupt;
```
- `makeSafeCallback` in the servant seems a bit jumbled and is hard to read. Consider breaking it up into several statements. Also, I think you can make it shorter by using lambdas and appropriate captures. For example, you're binding `weak` to the argument `std::weak_ptr<Servant> weakServant` [here](https://github.com/TUM-LRR/era-gp-sim/blob/feature/task-scheduler/include/core/servant.hpp#L73), even though you could simply capture it in the capture like so: `[weak] (....) {}`.
  Also, `bind` is actually not  necessary in C++14, lambdas do the job just right. See my personal notes [here](https://github.com/peter-can-write/cpp-notes/blob/62cf2de0374ab4c0218ba17431a79ca7b8fdcec4/plain/prefer-lambdas-over-std::bind.txt) and consider using lambdas only (though `bind` is fine, since it does the job).
- In `proxy.hpp`, I recommend using more `using` aliases. `std::promise<std::shared_ptr<Servant>>` is really hard to read compared to, say, `ServantPromise`.
- Please also document the classes. Like what `Scheduler` does as a whole class!
- `* TODO guide how to use this` ([here](https://github.com/TUM-LRR/era-gp-sim/blob/feature/task-scheduler/include/core/proxy.hpp#L152))
- I think for your own sanity you should also document `POST_CALLBACK_SAFE, POST_FUTURE` and co. better. It seems like the type of code where you come back a year later and you spend two weeks figuring out what it does, crying, hiring a detective team to figure out what it does, failing and end up burning your  computer and converting to buddhism to live on a remote island in the arctic.
- What is the point of the servant exactly, it just seems to be a light interface to the scheduler?
- Can you share a link to your reference for the active object pattern?
- Tests run fine :blush:
- Overall the code is great, I hope the thorough review helps to brush it up a bit :blush:
