### ISSUE TITLE
Implement Registers

### ISSUE THREAD

**Issue by ProfPille** [TUM-LRR/era-gp-sim#26]

**Comment by davschneller** [comment]
After looking into the memory implementation, lets also look into this... And I like it! It looks good, does not seem to have any problems (well, except docs and so, but ok), so here are just some suggestions/questions:
- It would be still great to put some of the calculations into methods. For example, the “get register for RegisterID“ appears all over the place, so this would do great in an own method, same goes for write. (and of course, set might be made up of get and put again, if wanted)
- Would be a `Register` class maybe useful to make the code a bit more organized? The data would be still kept separately, but the registers maybe have a reference (if this is still good C++) on the data object to then retrieve and store data to themselves, this could also help with the suggestion above. (but it is absolutely not necessary to do this, all is already ok, it's only a suggestion)
- Maybe the two aliasRegister overloads can be make use of another. (and not have the method coded twice, maybe even a default parameter would do)
- What it wasUpdated going to do? And what about the vector-set-string-thingy?

That's all I can see for now, keep up the good work!

**Comment by janschopohl** [comment]
I have started to review this issue.
- please add documentation to register-set.hpp and register-id.hpp. Document the private members, too.
- use clang-format
- what about the implementation of `wasUpdated` and the missing set callback method that I talked to you about on slack?
- The code compiles and the tests run :grinning:

The code looks fine otherwise, but I will look at it again after this is completed, as it will make the review much easier.

**Comment by davschneller** [comment]
Some more issues (though the rest of it seems to be fine):
- _(not relevant any more)_ Why not `unordered_set` instead of `set`? The first one is faster when it comes to retrieving single elements, same as with the map. **EDIT:** sorry, I have totally missed the for loop added the same day... Of course, then a `set` makes sense.
- A variable for `registerIterator->second` would make the code a bit easier to read in my opinion.
- Still, some methods could make use of another, for example the `get`s. And `set` could be a combination of `get` and `put` again.
- There is still the suggestion of singling out a `Register` class, but I do not think this is needed any more, the code looks pretty enough for it, in my opinion (but a `registerIterator->second` alias would make it really simple)

Apart from that, there is nothing to add, keep up the good work.

**Comment by janschopohl** [comment]
Thank you for adding the documentation and the callbacks!
I saw that you think some methods are not needed ([here](https://github.com/TUM-LRR/era-gp-sim/blob/feature/implement-register-set/source/core/register-set.cpp#L44) and [here](https://github.com/TUM-LRR/era-gp-sim/blob/feature/implement-register-set/source/core/register-set.cpp#L73)) and I think you can remove them.
Apart from this, I have nothing to add. 👍
