### ISSUE TITLE
Implement Memory

### ISSUE THREAD

**Issue by ProfPille** [TUM-LRR/era-gp-sim#27]

**Comment by davschneller** [comment]
Hi, so as you asked me already to look over it:

First of all, it looks great so far, good job! (of course, comments and documentation and tests are still missing, but this is not important right now as we are not in the review already)

I don't see any problems with the implementation (nor are there style guide violations as far as I can see), and I only have one suggestion for now (and some questions):

Currently, cellCount is private, though this one is a very interesting variable, as it shows the capacity of the memory! (so, mind a getter?)

The questions:
- Is it always like that, that the caller has to detect if there is an invalid access? Maybe this is something to discuss with the arch group... If they have to detect the invalid memory accesses, they would need the cellCount to detemine if an invalid address has been entered (so that the system can then throw a hard fault (if we get THIS far, so probably not) or just an error message). Or might it be helpful to implement a method which just returns false on an invalid access? (and “returns” the memory value as an argument)
- (almost the) same goes for unaligned access.
- How will several memory banks be treated? Let's take a complicated example: If we take the Arduino Due with its SAM3X8E chip, we got not only two banks (differently-sized) of RAM, but also two flash storage banks of which one is mirrored to address 0 (the others are NOT based on 0, all are in one memory plane). And also we got some area where you can write in values to choose what the peripherals (like an ADC, a real RNG or some UART and SPI outputs) should do. To break it all down: How would you handle different memory banks all within _one_ addressing scheme, some can be written to, some change dynamically, and some are read-only (and can only be written through some other registers). I guess many of this is architecture/implementation-specific and is for now irrelevant, but only as a possible question for the future...

So, to break it all down: Keep up the good work! (and sorry for the long text)

**Comment by janschopohl** [comment]
The code is well documented and you eliminated redundancy in the set method, this is really good. 👍
The tests run and I don't see any obvious problems, so I'm ok with merging this onto master.
