### ISSUE TITLE
Implement RISC-V Node Factories

### ISSUE THREAD

**Issue by ErikP0** [TUM-LRR/era-gp-sim#28]
Derive RISC-V specific subclases of all AbstractNodeFactory types

**Comment by ErikP0** [comment]
ast.hpp include and real commands will be used (instead of examples) when ready (see #32)

**Comment by k-lukas** [comment]
I found some issues:
- You should use a `std::unordered_map` instead of a `std::map`. They are faster when accessing elements by their key (See [reference](http://www.cplusplus.com/reference/unordered_map/unordered_map/)). And if you do so, you should use the `emplace` function to insert elements.
- Use, `std::begin` and `std::end` instead of the respective functions of a container. They are more extensible (See [reference](https://herbsutter.com/elements-of-modern-c-style/))
- You might use the doxygen syntax for documentation (that means `\param` instead of `@param`). I think it was discussed in slack.
- The define guard should follow the `<PROJECT>_<PATH>_<FILE>_H_` rule (-> `ERAGPSIM_ARCH_RISCV_NODEFACTORIES_HPP_`)

**Comment by ErikP0** [comment]
Hi,
an updated version is up. I integrated all the points you mentioned except the doxygen syntax commenting style one.  I think we should discuss this in the next group meeting, because there are also other files in the master branch, that use the `@...` commenting style.

**Comment by ProfPille** [comment]
I found some issues:

-You should use references as parameters as much as possible

-You should use the `\...` commenting style

-Your variable names are not very expressive, I suggest using `value` instead of `v`

-You should explicitly state whether you want your Destructor, Move-Constructor, Copy-Constructor defaulted, pure virtual or deleted
