### ISSUE TITLE
Improve the AST and add Load/Store Instructions

### ISSUE THREAD

**Issue by k-lukas** [TUM-LRR/era-gp-sim#30]
We've discussed about the syntax tree and found some issues. This has to be done in the abstract syntax tree and the concrete instructions, that are already implemented.
In addition load/store instructions may be added.

**Comment by k-lukas** [comment]
I forgot to add the issue id to the commit messages. The following commits have been made:
https://github.com/TUM-LRR/era-gp-sim/commit/bbb640cfe24cef3d6cc6b3f5c8acef9614075038
https://github.com/TUM-LRR/era-gp-sim/commit/f4d93e3d01fe28f3213527e73bde718537a63af4
https://github.com/TUM-LRR/era-gp-sim/commit/d3dc36faf09b2451bc4735f697466c8690e6ca1a
https://github.com/TUM-LRR/era-gp-sim/commit/e596899d69d9b418ced9b21e13ffcca764c02f20
https://github.com/TUM-LRR/era-gp-sim/commit/3161955acfc343e0064e44ba6205c1c554ea7a93

**Comment by yuriyarabskyy** [comment]
All good to go! I only have one question left: in order to assemble a command we need to access a `HashMap(command id -> assemble function for a specific format)`, which should be defined in the architecture class I guess, so we should probably add a reference to the architecture object as a parameter to the assemble method or maybe directly a reference to the AssemblerFunction defined on [my branch](https://github.com/TUM-LRR/era-gp-sim/blob/feature/define-bit-assembler/include/arch/common/instruction-assembler.hpp).

**Comment by k-lukas** [comment]
Hm, I'm not sure, if that is a good idea. That would mean, that the caller of the `assemble` method must known, which format the underlying instruction has. In fact, an instruction knows, what format it supports, so I don't think is necessary to have a mapping between the commands and your assemble function. Every instruction node could just call it's respective assemble function, so no mapping would be needed.

**Comment by riedersa** [comment]
The Code seems to be okay. Your own Group should know, wether it works like it should do. But may there be as many Todos?

**Comment by k-lukas** [comment]
The problem is, that a lot depends on the actual implementation of the core. Expecially the instructions suffers from that... Hopefully the core will be ready soon.
