### ISSUE TITLE
Instruction Key Class

### ISSUE THREAD

**Issue by goldsborough** [TUM-LRR/era-gp-sim#33]

**Comment by ErikP0** [comment]
Hi,
I have reviewed `InstructionKey` and found no apparent problems of any kind.
As a sidenote I could not compile the whole project due to many compile errors (information.hpp contains an header "third-party/..." which was not part of the branch, furthermore the class `Information` is an empty definition, causing all the compile errors. I assume this is due to the WIP of #34 ?
Anyway, as this does not influence the behaviour of `InstructionKey`, from my point of view you can merge the class.

**Comment by goldsborough** [comment]
Yes, sorry, currently hacking a lot. I'll leave this feature open and close it when everything compiles! Thanks.
