### ISSUE TITLE
Implement AbstractNodeFactoryCollection

### ISSUE THREAD

**Issue by ErikP0** [TUM-LRR/era-gp-sim#36]
Convienience class that holds all AbstractNodeFactory types

**Comment by k-lukas** [comment]
Looks good, but could you explain why there is a seperate setter for every type of factory? Wouldn't it be more convenient to pass the factories in the constructor?

**Comment by goldsborough** [comment]
I recommend a factory method for the factory class (factory-ception) that takes the concrete types as template parameters and allocates the classes internally. Otherwise creating the classes first and then having to move them in manually will be quite a hassle. Try something like this:

``` C++
template<typename ImmediateFactoryTemplate, typename RegisterFactoryTemplate>
struct FactoryTypes {
  using ImmedateFactoryType = ImmediateFactoryTemplate;
  using RegisterFactoryType = RegisterFactoryTemplate;
};

using RiscVTypes = FactoryTypes<RiscvImmediateFactory, RiscvRegisterFactory>;

class AbstractNodeFactory {

  template <FactoryTypes>
  AbstractNodeFactory Create() {
     AbstractNodeFactory factory; 
     factory.setImmedateFactory(std::make_unique<typename FactoryTypes::ImmediateFactoryType>());
   // ...
    return factory;
  }
};
```

Then all I need to do is:

``` C++
auto factory = AbstractNodeFactory.Create<RiscVTypes>();
```

Give it a try. I can help with the template magic if you need any

**Comment by ErikP0** [comment]
I used setter instead of constructor arguments because
- ugly long constructor definition
- by using setter I can assert when somebody tries to set a invalid pointer; In the constructor I cannot assert this,  because a certain architecture does not use all factories (see RISC-V) and therefore cannot pass a valid pointer for the factory-types it doesn't use. On the other hand with the setter, the architecture simply won't call the setter of factory-types it doesn't use.
- If in the future there should be the need to add another factory-type, the constructor won't change and doesn't affect the old code

About the second suggestion, a factory-factory via templates:
I am sure that your suggestion will run perfectly, but in my opinion this is a bit too complicated. I'm afraid that you, me or (hopefully) another team in the future, hardly understand the code and therefore have a hard time using it.
I suggest the following:
I have changed the setters to be chainable, consider this example for the risc-v architecture

``` C++
AbstractNodeFactoryCollection riscvFactories;
riscvFactories.setInstructionFactory(make_unique<RISCVInstructionNodeFactory>())
      .setImmediateFactory(make_unique<RISCVImmediateNodeFactory>())
      .setRegisterFactory(make_unique<RISCVRegisterAccessNodeFactory());
//riscVFactories is ready to be used
```

For 386 architecture, you would just add two more setter-calls (for MemoryAccess and ArithmeticOP) and change the factory-types respectively.
In my opinion that procedure for creation is easier to understand.
If you cannot agree with me, let's talk about it at the next meeting or at slack :)

**Comment by ProfPille** [comment]
I found some issues:

-You should use references as parameters as much as possible

-You are copying unique_ptr, I'm not sure what happens, but it looks suspicious. Shouldn't the use of a unique_ptr suggest a transfer of ownership and therefore make the caller give up their ownership? (It may work for RValues though)

-You should use the `\...` commenting style

-Your variable names are not very expressive, I suggest using `_arithmeticOperationNodeFactory` instead of `_arithOpF`

-You should explicitly state whether you want your Destructor, Move-Constructor, Copy-Constructor defaulted, pure virtual or deleted
