### ISSUE TITLE
Implement conversion methods from memory values

### ISSUE THREAD

**Issue by TobiasHoll** [TUM-LRR/era-gp-sim#43]

**Comment by ProfPille** [comment]
This looks promising, minor improvements could be:

-conversion.hpp (l.29) shouldn't it be  `#include "core/memory-value.hpp"` instead of `#include "memory-value.hpp"`?

-conversions.hpp (l.81) how about `(8 - bitsPerByte%8) % 8` instead of  `(bitsPerByte % 8 == 0) ? 0 : 8 - (bitsPerByte % 8)`?

-conversions.hpp (l.104) `std::size_t bitsNeeded = std::min(8UL, bits - bitsConverted);` does not compile at mine, had to change it to `std::size_t bitsNeeded = std::min(std::size_t(8), bits - bitsConverted);` to run it!

-I don't see why you mask the padding bits to zero in conversions-test.cpp (l. 135)

-I suspect the `getByteAt` method does not work anymore ( `result` is never written to)

-compiling conversions-test.cpp gives me a few warnings:<details>
<summary>

warnings</summary>



```
1>c:\users\daniel\documents\visual studio 2015\projects\eragpsim\eragpsim\conversions.hpp(329): warning C4800: "uintmax_t": Variable wird auf booleschen Wert ("True" oder "False") gesetzt (Auswirkungen auf Leistungsverhalten möglich)
1>  c:\users\daniel\documents\visual studio 2015\projects\eragpsim\eragpsim\test-conversions.hpp(325): note: Siehe Verweis auf die Instanziierung der gerade kompilierten Funktions-template "MemoryValue convert<int64_t,uintmax_t>(T,std::size_t,Endianness,SignedRepresentation,std::size_t)".
1>          with
1>          [
1>              T=int64_t
1>          ]
1>c:\users\daniel\documents\visual studio 2015\projects\eragpsim\eragpsim\test-conversions.hpp(101): warning C4715: "`anonymous namespace'::toSigned": Nicht alle Steuerelementpfade geben einen Wert zurück.
```

</details>

**Comment by goldsborough** [comment]
- Tests OK
- @ProfPille, yes it should be `#include "core/memory-value.hpp"`
- You could already use the `Endianness` enum from [ArchitectureProperties](https://github.com/TUM-LRR/era-gp-sim/blob/feature/conversions/include/arch/common/architecture-properties.hpp)
- Do we need the mask here (~150): `result = static_cast<T>(unsignedRawValue & exceptFirstBit);`. It looks like you check if the first bit is set, and if not, you mask off all bits except the first bit. But it isn't set anyway (same thing for the case when it's set).
- You might as well just `&= exceptFirstBit`
- Please document what `SIGN_BIT` actually is
- Maybe it would be a good idea to comment on how the bit operations you perform achieve the result.

```
// If the first bit is set, flip all the bits prior to conversion, then
// negate the result (like one's complement) and subtract one
```

just describes exactly what the code below does. It would be more maintainable to explain why these operations, for example, transform a number into two's complement. For example, I think `static_cast<U>(~(value & exceptFirstBit) + 1)` should perform two's complement transformation too.
- You might want to put the whole thing into a namespace. Floating `convert` functions seem a bit hairy.
- Couldn't the conversions to MemoryValue just be constructors? 😊 
- I'm a big fan of refactoring, so 100-line functions are a red flag in my book. I think you could refactor the cases for one's and two's complement to make things more legible and maintanable.
- The tests still use `kConstant` instead of `CONSTANT`

Otherwise, since the tests pass and the code seems to be performing the right transformations, the rest is great :+1:
