### ISSUE TITLE
Beautify AbstractNodeFactoryCollection Interface

### ISSUE THREAD

**Issue by goldsborough** [TUM-LRR/era-gp-sim#44]

**Comment by ErikP0** [comment]
Hi,
from my point of view, everything looks fine.
I've got only one little remark: For what reason do the `NodeFactoryCollectionMaker::Createfor(...)`  functions names start with a capital letter. I assume this is because they are non-member functions? If not, bear in mind, that all the other (member-) functions in our code base start with a lower case letter.
Apart from that, you can merge this feature.
