### ISSUE TITLE
LightStrip output component

### ISSUE THREAD

**Issue by andizimmerer** [TUM-LRR/era-gp-sim#46]

**Comment by goldsborough** [comment]
* [These lines](https://github.com/TUM-LRR/era-gp-sim/commit/c213edabf20ad6e9d0471cc11bae8087e77f498b#diff-ebca2c79cf8dba3c39dbbfbb5a484534R73) are not very readable. Better make a utility function in the `Utility` namespace and use it instead:
```
  template<typename T>
  T roundToBoundary(const T& value, const T& boundary) {
    return value + ((boundary - (value % boundary)) % boundary);
  }
```
and then:
```
auto memoryValueSize = Utility::roundToBoundary(memoryContentBitList.size(), 8);
```
* Please make better use of the `auto` keyword :blush:, like [here](https://github.com/TUM-LRR/era-gp-sim/commit/c213edabf20ad6e9d0471cc11bae8087e77f498b#diff-ebca2c79cf8dba3c39dbbfbb5a484534R56).
* Use a range for loop [here](https://github.com/TUM-LRR/era-gp-sim/commit/c213edabf20ad6e9d0471cc11bae8087e77f498b#diff-ebca2c79cf8dba3c39dbbfbb5a484534R91):
s/
```
for (auto it = content.cbegin(); it != content.cend(); ++it) {
    contentList.append(*it);
  }
```
/
```
for (const auto& byte : content) {
    contentList.append(byte);
}
```
This works because `MemoryValue` has a `begin()` and `end()` function and template magic.
* I would recommend having an alias `using size_t = std::size_t` in the header and then skipping the `std::` everywhere else.
* `explicit` is only useful if the constructor can be invoked with one argument ( [here](https://github.com/TUM-LRR/era-gp-sim/commit/5d0314be1c0d239628c9eb3123aa4074d7395c5e#diff-22128bca5e7f8520bef9f50e698537f1R39) )
* The formatting in [LightStrip.qml](https://github.com/TUM-LRR/era-gp-sim/blob/5d0314be1c0d239628c9eb3123aa4074d7395c5e/source/ui/Components/Output/LightStrip.qml) is a bit off

Looks good otherwise!

**Comment by FelixOpolka** [comment]
Thank you for the review! I have implemented the changes you suggested. The formatting in LightStrip.qml however was the one suggested by Qt Creator's auto-formatting tool. Changing it manually would make future edits a bit more tedious.
