### ISSUE TITLE
Define AbstractNodeFactory

### ISSUE THREAD

**Issue by ErikP0** [TUM-LRR/era-gp-sim#5]
Define abstract factories for types instruction, immediate, register, memory access, arithmetic operation

**Comment by goldsborough** [comment]
Ich glaub `Node` wär intuitiver als `Vertex` :smile:

**Comment by ProfPille** [comment]
Hi, I've reviewed your code and it seems to be mostly fine. The only problems I might see there is:
- The Styleguide says the _#define Guard_ should look like this `<PROJECT>_<PATH>_<FILE>_H_`
- You might want to use `MemoryValue` when creating an Immediate Node
- We might want to discuss the acessmethods of the registers and the memory
- I suggest using a `constexpr` instead of using a `static const` for the `int ADDITION`
- You declare the pure virtual destructor `~AbstractInstructionNodeFactory()` I don't think that's correct.

**Comment by ErikP0** [comment]
Hi, thank you for your suggestions.
I've changed the parts you mentioned, please have a look if my changes were correct.

**Comment by ProfPille** [comment]
I can't find any more problems at the moment.

**Comment by k-lukas** [comment]
I found some other issues:
- You can add the issue ID to the commit messages, so the commits will be shown in the timeline of the issue. That makes it a bit easier to review your code.
- The license header is missing. Please add these lines at the beginning of every file of the project: [Link](https://gist.github.com/0xdelta/23caef3f365d7129e5d54d4d7415fd92)
- Thats more a point to discuss about: Is it really necessary to have a class for every factory method? I think it's enough to have a single class that provides all factory methods at once.

**Comment by ErikP0** [comment]
I added the license header, but left the point whether to have just one factory-class or to have one factory-class for each node-type unchanged (so atm 5 factory-classes).
If this decision causes problems in the future development, we can open another issue to change it in the future.
