### ISSUE TITLE
Define Memory Value

### ISSUE THREAD

**Issue by ProfPille** [TUM-LRR/era-gp-sim#6]

**Comment by davschneller** [comment]
Hi, I looked at your code, and there are some issues I think that are not unimportant (as I am your reviewer):
- `for(int i=width;i-- >0;)data.push_back(false);`: Have you considered `data = vector<bool>(width, false);`? :) (any way, isn't that for loop a bit sneaky? Why don't you put the `--` after the second semicolon?)
- Please add the parameter names to the header... They are mentioned in the comments and we have now declared in slack, that we will always include them. :) (and it can be difficult to understand otherwise)
- `data` should be `_data`, according to our styleguide.
- Bracket layouts are sadly not consistent over the two files. (tried to run clang-format?)
- If I am correct, you might also have to add the license header to the files.
- There is no class description (as comment). :(
- The cpp feels a bit empty... But I don't know myself something to add as comments right now.
- Maybe more to follow...
- Some of these things might also apply to your other branches, so please consider them also there.

**Comment by ProfPille** [comment]
Thank you for your criticism
- Yeah, I use `data=std::vector<bool>(width,false);` in the version on my harddrive, but haven't updated it yet, because I'm not even sure if this class will be used in any future version of the project.
-  `for(int i=length;i-->0;){foo();}` May result in one less Machine operation, depending on system and compiler
- Yeah I'm currently working on updating all my headers to include parameter names
- indeed, I'll change that
- What do you mean? I know there is one bracket starting in the next line instead of starting at the end of the method, but that's the case because combined they'd be 8_1_ characters long
- No, I haven't yet used clang format, I'm still struggling to compile googletest and everything is aweful, but I made sure my other branches are more 'aesthetically pleasing'
- Yeah, I kinda should add a class description
- The cpp isn't meant to do very much and many say it does way too much

Sadly the main problem is this branch may be closed completely and therefore I haven't updated it lately

**Comment by davschneller** [comment]
Ok! I won't comment then anything any further until it is decided over the life of this branch.
But, just one short notice: I'm not a software engineering expert (especially not with C++), but: I don't think, your optimization (point 2) is worth it, it just makes the code a bit more unreadable, in my opinion. I mean, we got good compilers today. (here's something to read I though was quite good: http://www.flounder.com/optimization.htm)
Please correct me, if I oversaw something critical.

**Comment by davschneller** [comment]
Hi again! Seems like this branch will live longer... So let's review again... Looks good, here are some suggestions:
- Shouldn't be the doxygen in  a bit more completed?
- It would be really nice to have some more comments! For me, it is difficult to read and to understand the code like this, sorry... (and some of the code seems to be a bit redundant, mind some internal methods? I mean code like: `((_byteSize / 8) + (((_byteSize % 8) > 0) ? 1 : 0))`. (what is this actually? I am a bit confused by the byteSize and byteAmount as it sounds so similar...  Is it possible to make it easier to distinct between byteSize and byteAmount? At least to me it sounds like it could be interpreted to be the same... How about byteSize and byteCount or byteLength and byteCount? But that's just a personal oppinion.)... And so on. Just to refine some redundant stuff. Makes the code much more readable. Sorry for the nested brackets, this made my comment basically difficult to understand...)
- What about the test file in the branch? Is it still in use?
- The Travis build fails but is seems like it fails for everything we do right now.
  That's all for now from my side. Bye!

**Comment by goldsborough** [comment]
(Travis is not setup yet until I merge my branch)

**Comment by ProfPille** [comment]
Thank you for your feedback!

-I may look into trying to make the documentation more readable

-We discussed weather we use this model or a different more advanced one and we called the resulting methods 'basic modlo'

-I maybe should centralize some of these calculations / Add comments saying what they  are exactly doing

-byteSize is the size of a byte in bit, byteAmount is the number of bytes in the MemoryValue

-Yes, 'test-memory-value.inc' is the current test for the memory value and I encourage everyone to test it

**Comment by davschneller** [comment]
Hi again! I just wanted to ask, when your improved version is available. I am looking forward to seeing it, because I would really like to unterstand what you are doing with your code!
Anyways, I have looked at it again and I got some additional questions:

What is the giant array position determiner in e.g. `put` supposed to do? As far as I understood it, we are looking for the physical byte (I am just going to call it like this, the one we got in memory explicitly), where our logical byte begins which contains our address. Then we add up the rest to get to our specific byte where our bit address is positioned.

But, if we just want to determine the index of a byte, where a bit is located, couldn't we just do `address / 8`? (similarly `address % 8` for the testOr) Or is there some special behavior with packing which I have overseen? If not, the method would boil down to something like `if (value) _data[address / 8] |= (1 << (address % 8)); else _data[address / 8] &= ~(1 << (address & 8));` (with formatting, of course) What is actually the purpose of `testOr` and so on, when you can just write it explicitly in? (`testOr[i] = (1 << i); testAnd[i] = ~(1 << i); testEq[i] = (1 << i) - 1;` that's what they should look like if I am not mistaken)

I guess the expression `((_byteSize / 8) + (((_byteSize % 8) > 0) ? 1 : 0))` wants to determine the ceiling of ((float)_byteSize / 8)... But couldn't you just write something like `(_byteSize + 7) / 8`? And what about an extra method for this recurring calculation?

What also does `set` want to do? It looks to me like if it is be like `put`, but with the previous value returned... Why do you then do a lot of ifs and so on? I'd really like to know, thanks in advance!

To the `==` and `!=` operators: why don't you derive one from the other? (like `return !(first == second);`) The comparisons seems to do the same thing except for the return values. Probably, the loop could be a bit more easier to read (but that's just a personal opinion), if you put the last statement which is only executed on the last byte outside the loop (and test, if the array size is bigger than zero, of course), that would make the loop body much smaller.

For the tests: shouldn't be the file ending like `cpp`? According to the slack post you showed us, the tests took pretty long, in my opinion... I don't know if somebody else does it like me, but I like to run the tests pretty often, and if I always have to wait more than a minute (reminds me of Arduino testing...), it would be pretty... Nah, I don't know. Wouldn't it be possible, to provide a fast and a slow version of the tests?

Just another thing which might be just for beauty: I mean, wouldn't it be possible, to make the class not fixed on a 8 bit wide integer, but variable (w/ templates and so on)? I do not know at all if this will ever be needed, but it would look more general... So just as a suggestion that might not be needed at all in the future.

Sorry, if my criticism or so is too harsh...

**Comment by ProfPille** [comment]
Thank you!These are some very good questions.

My new version should be availiable soon. I'm just not yet satified with the improvement I made and still havent meade enough comments to help understanding it.

The giant array index does as this (VByte refers to virtual Byte): 
`(address / _byteSize) * SizeOfByte(_byteSize) + (address % _byteSize) / 8`
`(indexOfTheVByte   ) * SizeOfAVByteInByte    + offsetWithinTheVByte`
And no I can't just do `addres/8` because our values are internally padded and we don't always have a `_byteSize` of 8 bit

Yes, `set` exactly does what you are saying and it does it like this `(bitAt(address) == value) ? value : ( !value & flipBitAt(address))`

Yeah I was eventually going to do that. I was experimenting with trying different algorithms for them, but ended up using the same. For thee loopthing, there is more than one "last byte of a byte" `MemoryValue(100,7)` completely consists of "last bytes" for example.

The way I read the Styleguide files you include but that don't declare a class should be `.inc`

There are lots of constants one can change to make the tests faster and slower. `constexpr std::size_t scale = 1` for example as scalar factor. Most tests don't take that long on my computer, except for the death test and I'm not sure how to speed that one up.

Using templates would be possible, primarily one would have to change every occurance of `8` to `SizeOf(T)*8` I don't think it's necessary though. The user shouldn't see the datastructure very often anyways. They may use a `std::vector` to construct a MemoryValue, but I don't recommend doing that. On the other hand it might speed up some methods in the MemoryValue and the conversions.

It's fine, I love a good set of questions on my code

**Comment by davschneller** [comment]
Ah, thanks, I did not know that you wanted to pad it like this.

Just two more questions/hints:
- Why is `set` then written in this way and not like: `auto prev = get(address); put(address, value); return prev;`? (in my opinion that would be more readable, but ok)
- Everybody right now seems to be using `-test.cpp` or `-unittest.cpp`, that's why the `.inc` confused me a bit... Would you mind changing it this way?

But that's it, anything else I can only tell you when I see the new version. See ya!

**Comment by davschneller** [comment]
Hi again! Yes, this new commit looks even better! (again, would you mind to consder my two questions above?)

Though, as far as I can see, you still have to merge master into your branch. ;)

In my opinion, the statements _could_ be simplified and split into methods even further, but I won't block from now on about that. (though it would be nice to split the `set` return statement a bit more, because it looks still a bit complicated right now... Or comments would help!)

The only thing left that would be really nice, to have small descriptions at the parameters.

But all these may be some things to consider, but I do not want to delay this feature any longer (after all, it is really essential). So if you might have a look the things mentioned (then you have my ok) and the second reviewer (should be Jan) also agrees, then it can be merged.

**Comment by davschneller** [comment]
I'm gonna help you a bit (as you have a lot of work already done yesterday, great! It was not that much left to do so). Travis now works, I have tried to polish the code a bit and made the tests a bit more light-weight, so they now run under 200 ms on travis (see build 119 as a reference, the death test has been disabled for now b/c it did not seem to work and it took REALLY long...).

By the way, in the scripts folder is a script named adjust-filenames.py (or so) which accepts files and makes their includes look right, at least it should, no warranty. (it removes like Windows-style includes with '\'-type slashes, b/c travis does not like that)

So obviously, I am now ok with the branch. If the other reviewer is too, it will be merged immediately.

**Comment by davschneller** [comment]
Jan has agreed, the MemoryValue is now on master.

**Comment by janschopohl** [comment]
- add proper documentation to the private members, for example:

```
/** The size of the MemoryValue in bits */
std::size_t _size
```
- documentation for the write method ([here](https://github.com/TUM-LRR/era-gp-sim/blob/79f69519b127c3c5862e855943f90b6718ead6a3/include/core/memory-value.hpp#L159))
- you might want to consider documenting testOr, testAnd, testEQ, write0 and write1, and moving them to a common location
- please avoid redundancies in `set()` by doing something like  `oldValue = get(...); put(...); return oldValue;`
- consider documenting the tests
- the tests pass :smile:

**Comment by davschneller** [comment]
Hi again also from me, so let's look over this once more (and hopefully it's also the last time). So, let's see:

**MemoryValue file**
- Jan has already suggested some really good points
- Apart from that: I do not understand the advantage over using these testWhatever arrays (and the writeBit ones) over just inlining the expressions, and the latter seems easier to understand for me. The thing is: I think it is difficult to understand what the arrays should mean, explicit calculation would clarify here. (for example: with testEq somebody would probably never suspect that it is meant to be a mask which contains all bits up to the specified one, excluded) And I do not think there is any performance improvement (if anybody thinks of it) over using the direct expressions (e.g. `(1<<i)-1` instead of `testEq[i]`) Just my two cents about it.
- There could be even more comments. ;) (I like it green)

Except that, it is fine, so let's go to the **Conversions file**:
- First of all, we need comments, comments, comments, and documentation for all and everything.
- Secondly, the `A`, `B` and `C` suffixes are a bit confusing... Better naming would be really great here!
- Same goes for the provided functions. Also, as they are constants, should be written in `UPPER_CASE_MACRO_STYLE`.
- I still do not understand why there are two versions for a sgn function, depending on the convert template.
- A namespace might be nice, we got freestanding variables and functions here... (I do not know if this is good or not, but it would be nice to have functions which can be used equally grouped, similar to the old namespaces)
- Do you really need method overloading for `convert`? Wouldn't be rather default parameters be sufficient? Would reduce the code a bit...
- Some very important thing for readability: those functions are a bit hard to decode. A `using` directive helps a lot. You could even go further and make the `typename std::enable_if<std::is_integral<T>::value, T>::type` more easier to read if you got in some place something like `template<typename T> using IntTypeBarrier = typename std::enable_if<std::is_integral<T>::value, T>::type` (see my parse-strings branch or whatever it is called for something similar in action, definition is in utility.hpp), then use it by replacing your previous statement with `IntTypeBarrier<T>`. (hopefully this was a correct use of templates...) Might look nicer in a function definition, if there is not a such a long type checking thing there, in my opinion.

Hopefully, my suggestions help you a bit (though there are a bit large...). Well then, until next time! And just saying, I really like the idea of making the sign and the byte order and so on more flexible than just relying on some enum.

Bye!

**Comment by janschopohl** [comment]
I suggest moving the conversions to another branch and reviewing them separately with comments on the correct issue. To my understanding, the conversions are not finished yet.

**Comment by davschneller** [comment]
Hi, so to not delay any longer, Jan and I have decided to let you merge this to master, though not all of our suggestions were considered. (if anyone of the rest of the group wants them considered though, then we can probably fix this later, but for now, it should be sufficient, and most of all, it is working)

So, you shall pass (at least from my side).

**Comment by davschneller** [comment]
So, as this has been merged, I am going to close it. If anyone wants to change something small, it could be a new issue or if there are fundamentally changes, this might be reopened (or also a new issue).
