### ISSUE TITLE
Errors codes for instruction validation

### ISSUE THREAD

**Issue by k-lukas** [TUM-LRR/era-gp-sim#60]

**Comment by ErikP0** [comment]
Hi,
I have reviewed your code and found some issues
- In the implementation of `ValidationResult` the `bool` success and the message can contradict each other: The call `ValidationResult::fail("")` would create a object, where `isSuccess()` returns false and `getMessage()` returns `""`, which indicates a successful validation (following the documentation of the member function).
  In my opinion you should focus on one member (either success or the message) and add asserts to the other member, asserting illegal arguments/calls etc.
- In the following classes, the `ValidationResult` is not returned in the `assemble()` member function: abstract-register-node & register-node. They also do not compile and seem to do the same... As this isn't your fault (I just found them while looking for places where the ValidationResult should be used) I suggest that a refinement/refactoring of these two classes should be a new issue and should not be resolved in your feature
-  As far as I understood the message when failing the validation is more or less directly displayed to the user and should therefore be understandable (e.g. for the instruction-node I suggest that instead of using "Integer instructions must have exactly 3 children", "This arithmetic instruction must have exactly 3 operands" would be better understandable error message for the user). So please have a look at the other messages in immediate-node, integer-instructions and load-store-instructions
- You may as well adapt the `arch-riscv-integer-instruction-tests` in terms of using the `ValidationResult`

**Comment by k-lukas** [comment]
- Are you sure you reviewed the correct version of the `ValidationResult`? It's true, there was an older version that only used the message as indicator, if the validation succeeded/failed. But in the current version (Branch feature/error-codes-3) a `bool` was added to prevent this ambiguity.
- I added the correct return value to both classes, but one of them should be removed, right.
- Good point with the messages. I slightly changed some of the them, but a bit of optimisation will still be needed, when integrating the messages into the GUI. We'll do that, if the GUI is ready.
- The tests were adapted. Note that the tests still fail due to issues with `assemble()` method.

**Comment by ErikP0** [comment]
Ok your changes look good, the messages may need some work, maybe we should give more info like "Usage: add destination register immediate", but let's do that when integrating into the gui.
We will have to find a solution to fix or exclude the failing tests in the hangout, because in my opinion one should not merge a feature where something does not work :)
But apart from that everything looks fine.
