### ISSUE TITLE
Control Flow Instructions

### ISSUE THREAD

**Issue by goldsborough** [TUM-LRR/era-gp-sim#66]

**Comment by ErikP0** [comment]
Hi, I have reviewed your code.
First of all, your branch does not compile, neither on my side nor in [Travis](https://travis-ci.org/TUM-LRR/era-gp-sim/builds/162649493). Therefore I could not run your tests.
- In `AbstractBranchInstructionNode::getValue(...)` and in `AbstractJumpAndLinkInstructionNode::getValue(...)` I suggest to insert a `assert(validate().isSuccess())` before accessing the children-vector. One might otherwise access a invalid index
- `AbstractBranchInstructionNode` and all jump-instructions as well as the tests use the programcounter-id as a string literal. You may want to use the `PROGRAM_COUNTER` constant from #71
- When checking for the types of the operands in `::validate()` in all your instructions, I suggest to use `InstructionNode::requireChildren(Type, index)` for this task. It is used in the other instructions to validate.
- Your implementation of `AbstractBranchInstructionNode::_validateResultingProgramCounter`  and all jump-instructions`::_validateResultingProgramCounter` just returns true at the moment. There is code that is commented out. You may look if this is intended.
- You could make some of the comparison predicate lambdas used constructing the branch-instructions `static`
- `control-flow-instructions.hpp` and `control-flow-instructions.cpp` can be removed, they are empty
- We may not need an extra class for the `J`-instruction. It could be filled with `x0`-Register operand when inserting the lambda into the `_instrucionMap` in the `riscv::InstructionFactory`
- `branch-instruction-test::testUnsignedBranch(...)` you still use as template argument `signed32_t`. Is this intended ?
- `jump-instruction-test` in line 114, you use _x_ `& -1`. ANDing 1s does not change _x_, does it?
- `jump-instruction-test` in line 180 contains a `TODO`. Is it intended to omit that?
- In `riscv/instruction-node-factory.hpp/cpp` I sugggest having the "instruction map filling" in one file for a better overview. At the moment load/store are set up in the source file, integer- and the control-flow-instructions are set up in the header
- About `Utility::occupiesMoreBitsThan(...)` and its uses: I see a possible error in the following situation:

``` C++
//e.g. AbstractBranchInstructionNode::getValue()
//let SignedWord = int32_t; the MemoryValue of _child2 is 0xF 0000 0001
auto offset = _child<SignedWord>(memoryAccess, 2);//offset = 1
    if (Utility::occupiesMoreBitsThan(offset, 11)

//Utility::occupiesMoreBitsThan(value, numberOfBits)
auto boundary = static_cast<std::int64_t>(1) << numberOfBits;
  return (value < 0) ? value < -boundary : value >= boundary;//return false
```

We do not know how the conversions will handle a `MemoryValue` that is greater than the type to convert to. It will most likely just use the range of the type and cut out the rest.  So `0xF 0000 0001` will become `0x0000 0001` and the upper `F` will get cut out. Then obviously 0x1 does not occupy more than 11 bits. But the `MemoryValue = 0xF 0000 0001` does.
We have seen that checking for a range of a `MemoryValue` is not a trivial task. The features #64 and #71 also had problems with a similar task. They used index-based access to single bits to check for the range, but this aproach is dependent on how the `MemoryValue's` indexing works.
I think we should transfer this problem into another issue and write one generalized utility.

**Comment by goldsborough** [comment]
1. Thanks, I inserted them. Theoretically they are unnecessary since the nodes should be validated before anyway, but because assertions are "free", why not.
2. Is that constant really necessary? It would make sense if we planned on ever changing the program counter's name. But do we?
3. Thanks, but I'm using `_compareChildTypes`, which takes a list of types and ensures the childrens' types match those.
4. `_validateResultingProgramCounter` returns true because I'm still waiting to see if we can have `memoryAccess` in the `validate` method, which is required to access the program counter to see if we are trespassing any bounds.
5. Do you mean make the lambdas `static` and them pass them in the constructor? Are you sure that's useful since we're only using them once (when passing in the constructor)?
6. Thanks, I removed the `control-flow-instructions.cpp`. The header is an "aggregate header"so we can include both jump and branch instructions at the same time.
7. Thanks, I changed it to unsigned. Very thorough, thanks a lot.
8. Careful, it is `& ~1`, not `& -1` (all bits but the first set).
9. Yes the todo is because of (4).
10. Thanks, I'll actually refactor the whole factory map into a new file.
11. I see. I think I have an idea (talk in 30 mins).
