### ISSUE TITLE
GUI project creation

### ISSUE THREAD

**Issue by janschopohl** [TUM-LRR/era-gp-sim#68]

**Comment by goldsborough** [comment]
Hi,
- The include guards are slightly inconsistent, e.g. `INCLUDE_UI_EDITOR_QPROJECT_H` in `ui/project.hpp` and `ERAGPSIM_UI_UI_HPP_` in `ui/ui.hpp`. Please stick to: `RELATIVE_PATH_TO_FILE_HPP` _without the underscore_, e.g. `UI_EDITOR_PROJECT_H`. That was a bug in `new.py`.
- I think it would be better to leave the `Q-` prefix to Qt things and not use it for our own classes.
- Some of [these includes](https://github.com/TUM-LRR/era-gp-sim/blob/15bd92d7a4654f95b6f8990bfb095e1b6dc1f4dd/include/ui/ui.hpp#L23-L31) seem unused?
- Log output from running:
  `
  qrc:/Components/Snapshots/SnapshotList.qml:177: ReferenceError: snapshotModel is not defined
  file:///usr/local/Cellar/qt5/5.6.1-1/qml/QtQuick/Controls/TreeView.qml:94:16: Unable to assign [undefined] to QAbstractItemModel*
  qrc:/Components/Register/Register.qml:52: ReferenceError: registerModel is not defined
  file:///usr/local/Cellar/qt5/5.6.1-1/qml/QtQuick/Controls/TreeView.qml:94:16: Unable to assign [undefined] to QAbstractItemModel*
  qrc:/Components/Register/Register.qml:52: ReferenceError: registerModel is not defined
  `
- What about module/extension selection for an architecture?
- Maybe add _bytes_ to the `Memory size`
- Can you hide the toolbar when creating a project and only show it for project tabs with created projects? It seems weird that there are play/stop buttons and bin/oct/dec/hex selectors, when I haven't even created a project yet.
- It would be better to make the UI components fixed size or give them a maximum size. The `Create Project Button` taking up half the screen is a bit absurd.

Looks good otherwise, from what I see (it runs).

**Comment by andizimmerer** [comment]
I finally found some time to take a look into it. I can't find any further issues! Well done!

**Comment by janschopohl** [comment]
Ok, thanks for the review. I have already fixed some things and will update the project creation screen later. As mentioned on slack, information about the architecture and extensions will then be loaded from a file.
