### ISSUE TITLE
execution loop

### ISSUE THREAD

**Issue by janschopohl** [TUM-LRR/era-gp-sim#72]

**Comment by goldsborough** [comment]
`era-gp-sim/source/core/parsing-and-execution-unit.cpp`:
- Slightly inconsistent use of `int` vs `std::size_t`. I would define a `using size_t = std::size_t` in the header and only use that.
- Consider using more type aliases for the long callback function types. You could declare a templated alias like `template<typename T> using Callback = std::function<void(const T&)>` or even `template<typename T> using ListCallback = std::function<void(const std::vector<T>&)>` since you seem to use those often.
- Try to document better what you are doing, either through inline comments or by writing a sentence/paragraph in the extended documentation (after the first newline). There's quite a lot of non-trivial code so it will be useful in the future to get a quick idea of "this function does X and Y because Z to achieve Potato`
- What's with `AbstractSyntaxTreeNode::length()`?
- Your code doesn't compile on my machine:

```
error: braces around scalar initializer [-Werror,-Wbraced-scalar-init]
, _stopFlag(ATOMIC_FLAG_INIT)
```

This is because this initializer is intended to be used as `flag = ATOMIC_FLAG_INIT` and then expands to (_under my implementation_) `flag = {false}`. Since there's no alternative for the constructor, I'd say go ahead and just declare initialize it with `false`, since this is not yet critical area anyway (or clear the flag in the constructor).
- Commit 51ff0e2e57e62c59700f7a3529445e09a1423d6b contains 98 insertions and 98 deletions, yet 100 would have been a much nicer number. This is unacceptable
- To be continued *

**Comment by goldsborough** [comment]
- I think we can split [this long function call](https://github.com/TUM-LRR/era-gp-sim/blob/992ee3848002ebec3ec1984c6cce4ea4ab121dde/source/core/parsing-and-execution-unit.cpp#L128) into an assignment (`auto programCounterValue = conversions::convert ...` and then the function call, for readability
- Have you explored ways to optimize [this linear lookup](https://github.com/TUM-LRR/era-gp-sim/blob/992ee3848002ebec3ec1984c6cce4ea4ab121dde/source/core/parsing-and-execution-unit.cpp#L122). How often is this called? If it is called often with the same command list, keeping a `static` cache where you insert `(line, command)` pairs once you found them, or even doing a whole internal preprocessing step of creating all such `line<->command` mappings would make this faster. Isn't that actually what `_addressCommandMap = _finalRepresentation.createMapping();` is [here](https://github.com/TUM-LRR/era-gp-sim/blob/992ee3848002ebec3ec1984c6cce4ea4ab121dde/source/core/parsing-and-execution-unit.cpp#L146)?
-  `if (_finalRepresentation.errorList.size() > 0)` [here](https://github.com/TUM-LRR/era-gp-sim/blob/992ee3848002ebec3ec1984c6cce4ea4ab121dde/source/core/parsing-and-execution-unit.cpp#L102) might be better written as `if (!_finalRepresentation.errorList.isEmpty())` or even as `if (_finalRepresentation.hasErrors())` if those interface additions to the final representation are possible
- Since you're accessing `_finalRepresentation.commandList` so often it might be better to just store a reference to it as `_commandList`
- Note that one caveat of `for (auto&& x : ...)` is that it doesn't make values`const`, so doing `for (const auto& x : ...)` is actually stronger if you don't expect rvalue 
- If you don't explicitly want to check for bounds errors with `at()`, use `[]` because the bounds checking is overhead. And if you want to do bounds checking, that should be done with assertions in the function itself, like [here](https://github.com/TUM-LRR/era-gp-sim/blob/992ee3848002ebec3ec1984c6cce4ea4ab121dde/source/core/parsing-and-execution-unit.cpp#L78) in `commandList::operator[]`

**Comment by andizimmerer** [comment]
Hi,
apart from what peter already said, I can't find any more issues ^^
Well done
