### ISSUE TITLE
Custom assert

### ISSUE THREAD

**Issue by goldsborough** [TUM-LRR/era-gp-sim#75]

**Comment by goldsborough** [comment]
- Le code:  79e3fbc328ccf10202ea80b9f5764ad5248ff6da
- Das tests: 35761f137ebed9886ca665c90749c7dfe1ebc522

**Comment by davschneller** [comment]
Hi, first of all: This looks great!
Here are a few suggestions/questions:
- With gtest somehow it only tells that an exception has been thrown, but not the `what()` (or I am compiling somehow wrongly)... Would it be possible to show it otherwise?
- Is it maybe useful to also include some function name (maybe with parameters)? (though this might feature compiler-specific extensions, if `__func__` is not enough...)
- Currently it is the way that if somebody inserts a preprocessor macro into the `assert::that`, that it will show the name of the macro. Is it planned like this or should the macros expand? (this will be rarely case, though)

But apart from that, there is nothing I could complain about, everything is well-documented (well, except unicorn maybe, if this needed some documentation), and commented.

**Comment by goldsborough** [comment]
Thanks for the review.
- That's probably a gtest problem. But I can print it inside the constructor.
- I did have `__func__` first, but unfortunately it will print `operator()` because it is inside the lambda, and then inside `execute`. It works for the regular `assert` because it's just the `if () {}` without all the functions. But I think the condition + line are fine.
- I see the issue, but the nice thing here is that `#condition` will stringify code conditions, so you can actually see the `iterator.first == 7` inside the error. I think that's more useful than expanding macro names and we have to pick one since there's no logic for checking if something is a macro

**Comment by ProfPille** [comment]
I really like this! It looks great!
The only suggestionI have is a Gtest-mode that utilizes the GTest-`FAIL()` instead of an exception.
Can't wait to use this!

**Comment by goldsborough** [comment]
The assertion now prints the message and I've added the `FAIL()` variant as `assert::test(condition)`. Since there were no other major issues, I will close and merge this issue so we can all start using it.
