### ISSUE TITLE
Introduce parser factory

### ISSUE THREAD

**Issue by kreudom** [TUM-LRR/era-gp-sim#85]

**Comment by davschneller** [comment]
Looking good! (sorry, I do not have much time for a long review)
Just one thing: Shouldn't be the map be made `const`? Otherwise some might delete existing parsers, I think... But if parsers should be able to be added, of course one could do a variable in the `.cpp` and use methods then, but this is already the only thing I currently can think of.
Keep up the good work!

**Comment by kreudom** [comment]
Thanks, I implemented your suggestions (0789aaf).

**Comment by ErikP0** [comment]
This one looks good as well.
One point to think of: I think a missing parser for a certain architecture denotes a programming error rather than a wrong user input/configuration error and should be asserted (instead of returning a `nullptr`).
If you discussed the interface with the gui-team and they want it like that, then the current way is fine as well

**Comment by kreudom** [comment]
Thanks, I implemented your suggestions. I'd appreciate it if you had another look.

**Comment by davschneller** [comment]
From my side, there's nothing to complain any more.

**Comment by ErikP0** [comment]
Looks good :)
