### ISSUE TITLE
Implement new conversions

### ISSUE THREAD

**Issue by ProfPille** [TUM-LRR/era-gp-sim#87]

**Comment by davschneller** [comment]
Hi,

so here's the review, let's dive directly into it. First of all: it's looking good, here are my only left concerns:
- There are still TODOs in there, are these really needed? I mean, at least one of the enums the arch group should implement is already there the last time I checked (iirc). And the members could have some documentation in my opinion...
- Shouldn't the types aliased with `using` be first letter capitalized?
- For the constant variables, shouldn't they be completely uppercase or so? (and they need documentation and in my opinion a bit stronger names than just a letter suffix)
- Why are there so many different overloadings of `convert` (including `convertUnsigned`)? Couldn't it just be enough to have two in total (or maybe four, if we want to keep the enums?)? That would make the code simpler in my opinion. Also, if you have the constaint, that some convert methods only take little endians, it is a bit confusing, in my opinion.
- Is there really a struct for bigEndian (first letter should probably be uppercase) necessary? Why no lambda, a create function or something similar?

Also, clang-format would be nice. ;)

Looking forward to the changes, keep going!

**Comment by davschneller** [comment]
Oh, and clang does not like the conversions sometimes. (b/c of shift overflow) That's something that would be really nice to have it fixed.

**Comment by janschopohl** [comment]
I agree with the points of @DXIS and I want to emphasize that better, non-abbreviated names and more documentation would make the code a lot easier to read (Also do this in the tests please!).
- The code should be in a namespace
- there are a lot of global variables, which is quite bad style. One suggestions would be to use enums to decide how to convert the MemoryValues, instead of using the globally declared function objects.
- The code does not compile with clang, as mentioned before.
