### ISSUE TITLE
String-Memory value conversions

### ISSUE THREAD

**Issue by FelixOpolka** [TUM-LRR/era-gp-sim#96]

**Comment by riedersa** [comment]
I think it is okay. You could write a comment to the methods, which are written as a comment. But everything else seems to be fine.

**Comment by k-lukas** [comment]
Overall, the code looks good, but I have some smaller suggestions:
- Format the includes in the cpp file like this:

```
#include "common/string-conversions.hpp" // Associated header

#include <iomanip> // Standard Library includes
#include <sstream>

#include "core/conversions.hpp" // Includes from our project
```
- Use const references for parameters (e.g. `const MemoryValue&` or `const std::string&`)
- `std::string result = "";` is the same as `std::string result;`. I would prefer the last one
- In `toBinString()`: `string.insert(0, value)` is not very fast. I suggest to do it like this:

```
std::string result;
result.reserve(memoryValue.getSize());
for (size_t currentBitAddress = 0; currentBitAddress < memoryValue.getSize();
     ++currentBitAddress) {
  bool currentBitValue = memoryValue.get(memoryValue.getSize() - 1 - currentBitAddress);
  result.push_back(currentBitValue ? '1' : '0');
}
```
- In `toBinString()`: `result = result.substr(result.length() - memoryValue.getSize());` always returns result, doesn't it?
- Use `static_cast<int>(value)` instead of `(int) value`
- `std::vector<uint8_t> internal = memoryValue.internal();` will make a copy. Use `const std::vector<uint8_t>& internal = memoryValue.internal();` instead
- `toDecString()` should either be defined in the header (template functions can't be split into declaration & definition. In this case, everything compiles, because toDecString() is only called within string-conversions-cpp, but if you would try to call it from outside, it would lead to a linker error) or moved completely into the cpp file
- Use `std::intmax_t` and `std::uintmax_t` instead of `long long` and `unsigned long long` (they are defined in `<cstdint>`)
- `toUnsignedDecString()`: `long long intermediateValue = conversions::convert<long long>(memoryValue, conversions::standardConversions::nonsigned);` should be `std::uintmax_t intermediateValue = conversions::convert<std::uintmax_t>(memoryValue)` (that is a wrapper for the conversions). This also applies for the other functions, that use the conversions from the core.
- Remove code that is commented out (`toDecimalFloatString()`)
- You insert a prefix for hex, but no prefix for binary. Maybe you should add `0b` for binary literals
- std::stoi throws an exception, if the input string is malformed. That exception is not caught. Have you thought about that? For example, the gui could check for malformed input before calling the conversion functions
- Use unified initializer syntax (e.g. `MemoryValue{vector, size}` instead of `MemoryValue(vector,size)`)
- Every time you use iterators, use the new functions to access begin and end (e.g. `std::begin(container)` instead of `container.begin()`). That is more common in C++11

**Comment by k-lukas** [comment]
Thanks! Looks good now. From my point, it can be merged.
